/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_multimap_Map_ImmutableListIter_Native */

#ifndef _Included_io_multimap_Map_ImmutableListIter_Native
#define _Included_io_multimap_Map_ImmutableListIter_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_multimap_Map_ImmutableListIter_Native
 * Method:    numValues
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_io_multimap_Map_00024ImmutableListIter_00024Native_numValues
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_multimap_Map_ImmutableListIter_Native
 * Method:    seekToFirst
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_multimap_Map_00024ImmutableListIter_00024Native_seekToFirst
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_multimap_Map_ImmutableListIter_Native
 * Method:    seekTo
 * Signature: (Ljava/nio/ByteBuffer;[B)V
 */
JNIEXPORT void JNICALL Java_io_multimap_Map_00024ImmutableListIter_00024Native_seekTo__Ljava_nio_ByteBuffer_2_3B
  (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     io_multimap_Map_ImmutableListIter_Native
 * Method:    seekTo
 * Signature: (Ljava/nio/ByteBuffer;Lio/multimap/Callables/Predicate;)V
 */
JNIEXPORT void JNICALL Java_io_multimap_Map_00024ImmutableListIter_00024Native_seekTo__Ljava_nio_ByteBuffer_2Lio_multimap_Callables_Predicate_2
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_multimap_Map_ImmutableListIter_Native
 * Method:    hasValue
 * Signature: (Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_multimap_Map_00024ImmutableListIter_00024Native_hasValue
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_multimap_Map_ImmutableListIter_Native
 * Method:    getValue
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_io_multimap_Map_00024ImmutableListIter_00024Native_getValue
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_multimap_Map_ImmutableListIter_Native
 * Method:    next
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_multimap_Map_00024ImmutableListIter_00024Native_next
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_multimap_Map_ImmutableListIter_Native
 * Method:    close
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_multimap_Map_00024ImmutableListIter_00024Native_close
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
